apiVersion: apps/v1
kind: Deployment
metadata:
  name: talent-deployment
  namespace: vnplatform-graphql
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: talent-graphql
  template:
    metadata:
      labels:
        app: talent-graphql
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        application: mixed
      containers:
      - name: talent-graphql
        image: vnplatformbackendgraphql.azurecr.io/talent:83bc18767cec99be21912ebc9118a5f6d02b0916
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9500
        resources:
          requests:
            cpu: 1024m
            memory: 1028Mi
          limits:
            cpu: 2250m
            memory: 2256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: 9500
          initialDelaySeconds: 30
          periodSeconds: 10 
          successThreshold: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "90"] 
---
apiVersion: v1
kind: Service
metadata:
  name: talent-graphql
  namespace: vnplatform-graphql
spec:
  type: ClusterIP
  selector:
    app: talent-graphql
  ports:
  - port: 80
    targetPort: 9500
