name: must run on custom runner

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello from new runner'
      - run: echo $HOSTNAME
      - run: echo 'runnertestbranch'
      
      
      
      
