name: Trigger Specific Workflow

on:
  repository_dispatch:
    types:
      - trigger-specific-workflow-event

jobs:
  trigger-specific-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: <harish5128>/<custom-runner>
          event-type: custom-workflow-event 
